### ISSUE TITLE
Binary contains AVX instructions, incompatible with some processors

### ISSUE THREAD

**Issue by dsd** [flathub/net.sourceforge.atanks#4]
Testing on Asus E406SA (Intel Atom x5-E8000), atanks immediately crashes in GLOBALDATA::GLOBALDATA() with SIGILL.

The instruction being processed is VXORPD, which is an AVX instruction, not available on this CPU.

I believe this is caused by atanks' Makefile using `-march=native` for compilation.

**Comment by sat3ll** [comment]
https://github.com/flathub/net.sourceforge.atanks/pull/5#issuecomment-455836266

Can you try installing the test build and see if it fixes it?
